### PR TITLE
Amend Getting started episode

### PR DESCRIPTION
**Pull request by mahesh-panchal**
I started proof reading the getting started section, and then realised it became way too long.
I think everything after the first script section should be put somewhere else. Do you have opinions on when the
rest should be presented?

I also modified the DSL2 section to follow the Nextflow DSL2 conventions. I think this is something we should
encourage as it helps with readability. 

Lastly the code example has an issue. It performs a line count on a compressed file. How should we address this?
Modify the command to use `zcat` or use an uncompressed file?

### CODE REVIEW

**Comment by ggrimes** [comment]
I think zcat is the best option to save space
`zcat file.gz | wc -l`

**Comment by ggrimes** [comment]
I am writing a reporting episode and everything in the log section could be incorporated there.
The work directory could be a brief aside or covered in more detail in the log episode

**Comment by mahesh-panchal** [comment]
How should we best take care of the split off stuff here then? Shall we leave it in the spare file in this commit and move parts to appropriate places in other pull requests?

**Comment by mahesh-panchal** [comment]
Also are you happy with the episode content reordering?

**Comment by ggrimes** [comment]
I would like to include the Pipeline parameters section and the Process identification callout.

**Review by ggrimes — APPROVED** [review]

**Review by ggrimes — APPROVED** [review]

**Review by ggrimes — APPROVED** [review]

**Review by ggrimes — APPROVED** [review]

**Review by ggrimes — APPROVED** [review]

**Review by ggrimes — APPROVED** [review]

**Comment by mahesh-panchal** [comment]
> I would like to include the Pipeline parameters section and the Process identification callout.

Where?

**Comment by ggrimes** [comment]
It would appeat after the "Run a Nextflow script" in episode 1

**Comment by mahesh-panchal** [comment]
I've added back the part on pipeline parameters and process identification. 
I still think these should be removed though from getting started. 

I think it would be good to have a full episode on workflow parameterisation.
 - Explain the difference between `-` and `--`.
 - Parameter priority: Command line vs config file.
 - Advanced parameterisation: Reading in formatted input such as CSV files and YAML files. Tool configuration using Groovy Maps, etc. 

Process identification I think should be put elsewhere. It should be talked about when we go over the work folder. The question is where exactly to put this. Should we make a troubleshooting episode, where the work dir is explained, we
add this callout on process id, and how to use the `.command.sh` and `.command.run` files?

I've opened this up to merge if you're happy with the current state. I've shorted the parameter challenge because 18 files is unnecessary.

**Review by ggrimes — APPROVED** [review]

**Pull request merged**
