### PR TITLE
Coding practices episode

### PR DESCRIPTION
**Pull request by mahesh-panchal**
An episode on coding practices.
Should this be an episode, or scattered throughout the course?

### CODE REVIEW

**Comment by mahesh-panchal** [comment]
This looks like enough content for it's own page.

**Comment by ggrimes** [comment]
I agree,  I would add this as a separate episode.

**Comment by mahesh-panchal** [comment]
Anything else you think should be added (or reordered)? Aside from some exercises?

**Comment by sateeshperi** [comment]
recommend encouraging users to add `tag` and `labels` to processes

**Comment by mahesh-panchal** [comment]
> recommend encouraging users to add `tag` and `labels` to processes

@sateeshperi What are the benefits to this in terms of readability, maintainability, portability, reproducibility, or compute best practices?
Usually only one `tag` value appears per process while the pipeline is running or complete. Can you explain further why this is useful?
I'm also not sure what the clear benefit of using labels is in this context. What do you encourage?

**Comment by sateeshperi** [comment]
i thought enforcing them as we do in modules will help with debugging and config files....however as long as we cover them in the processes chapter they don't need to be in the best coding practices chapter

**Comment by mahesh-panchal** [comment]
I'll add in exercises later. Probably better to have the material in now.

**Pull request merged**
